// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

function drawToScreen(screen, size, position) {
  screen.fillRect(position[/* x */0] - (size[/* width */0] / 2 | 0) | 0, position[/* y */1] - (size[/* height */1] / 2 | 0) | 0, size[/* width */0], size[/* height */1]);
  return /* () */0;
}

function drawBody(screen, body) {
  return drawToScreen(screen, body[0], body[1]);
}

function draw(game, canvas) {
  var screen = canvas.getContext("2d");
  screen.clearRect(0, 0, canvas.width, canvas.height);
  return List.map((function (param) {
                return drawBody(screen, param);
              }), game[/* bodies */0]);
}

exports.drawToScreen = drawToScreen;
exports.drawBody     = drawBody;
exports.draw         = draw;
/* No side effect */
